# cloudbuild.yaml
steps:
  # Étape 1: Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/self-driving-prediction:$COMMIT_SHA', '.']

  # Étape 2: Pousser l'image Docker vers Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/self-driving-prediction:$COMMIT_SHA']

  # Étape 3: Déployer l'image sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'self-driving-prediction' # Nom de votre service Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/self-driving-prediction:$COMMIT_SHA'
      - '--region'
      - 'europe-west1' # Mettez la région choisie précédemment
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=1'
    env:
      - 'PROJECT_ID=$PROJECT_ID'

# AJOUTEZ CETTE SECTION options AU NIVEAU RACINE DU FICHIER YAML
options:
  logging: CLOUD_LOGGING_ONLY # Indique à Cloud Build de stocker les logs dans Cloud Logging
